### ISSUE TITLE
Issue with sd2k function

### ISSUE THREAD

**Issue by JimGrange** [eddjberry/mixturer#5]
Line 17 of sd2k function needs parentheses on the denominator. Currently, we get an error:

```
sd2k(0.3659424)
[1] 0.5295116
```

This value should return a K of 8. Correcting line 17 to the following fixes the issue:

  K = 1 / (R^3 - 4 * R^2 + 3 * R)

```
sd2k(0.3659424)
[1] 7.995975
```

**Comment by eddjberry** [comment]
This should be fixed now. Thanks @JimGrange
